// <auto-generated />
using System;
using CbarFormsApp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CbarFormsApp.Migrations
{
    [DbContext(typeof(RepoContext))]
    [Migration("20230416141347_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CbarFormsApp.Entities.ValType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NameForTime")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ValTypes");
                });

            modelBuilder.Entity("CbarFormsApp.Entities.Valute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nominal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ValTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ValTypeId");

                    b.ToTable("Valutes");
                });

            modelBuilder.Entity("CbarFormsApp.Entities.Valute", b =>
                {
                    b.HasOne("CbarFormsApp.Entities.ValType", null)
                        .WithMany("Valutes")
                        .HasForeignKey("ValTypeId");
                });

            modelBuilder.Entity("CbarFormsApp.Entities.ValType", b =>
                {
                    b.Navigation("Valutes");
                });
#pragma warning restore 612, 618
        }
    }
}
